language: node_js
node_js:
  - "4.2.1"

before_script:
  - npm install gulp gulp-util gulp-sass gulp-uglify gulp-rename gulp-minify-css gulp-notify gulp-concat gulp-plumber browser-sync gulp-gh-pages node-neat 
script: gulp deploy